export interface SalesClient {
  vertical: string;
  name: string;
  users: number;
  revenue: number;
}

export const rawSalesData: SalesClient[] = [
  { vertical: "FINANCEIRO I", name: "BRADESCO", users: 2777, revenue: 1538154 },
  { vertical: "GOVERNO", name: "BANCO DO BRASIL", users: 904, revenue: 1478799 },
  { vertical: "FINANCEIRO I", name: "ITAU UNIBANCO", users: 728, revenue: 1024930 },
  { vertical: "FINANCEIRO II", name: "XP INVESTIMENTOS", users: 375, revenue: 512712 },
  { vertical: "FINANCEIRO I", name: "SANTANDER BRASIL", users: 335, revenue: 424126 },
  { vertical: "FINANCEIRO I", name: "SAFRA C.V.C.", users: 144, revenue: 274791 },
  { vertical: "FINANCEIRO II", name: "BTG PACTUAL", users: 129, revenue: 236564 },
  { vertical: "FINANCEIRO I", name: "BANCO ABC BRASIL", users: 85, revenue: 225980 },
  { vertical: "GOVERNO", name: "MINISTÉRIO DA FAZENDA", users: 78, revenue: 185944 },
  { vertical: "GOVERNO", name: "CAIXA", users: 199, revenue: 441010 },
  { vertical: "FINANCEIRO I", name: "BANCO CITIBANK", users: 82, revenue: 155203 },
  { vertical: "GOVERNO", name: "BNDES", users: 54, revenue: 145650 },
  { vertical: "GOVERNO", name: "BANCO CENTRAL DO BRASIL", users: 68, revenue: 128727 },
  { vertical: "FINANCEIRO I", name: "BANCO VOTORANTIM S/A", users: 64, revenue: 104008 },
  { vertical: "FINANCEIRO I", name: "ÁGORA CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S/A", users: 303, revenue: 99398 },
  { vertical: "GOVERNO", name: "SECRETARIA DO TESOURO NACIONAL", users: 57, revenue: 95620 },
  { vertical: "GOVERNO", name: "PETROBRAS", users: 26, revenue: 84384 },
  { vertical: "FINANCEIRO II", name: "BRASIL PLURAL", users: 28, revenue: 79501 },
  { vertical: "GOVERNO", name: "CVM", users: 34, revenue: 79065 },
  { vertical: "GOVERNO", name: "BANRISUL", users: 32, revenue: 74643 },
  { vertical: "GOVERNO", name: "BNB - BANCO DO NORDESTE", users: 34, revenue: 71553 },
  { vertical: "GOVERNO", name: "CAIXA PREV.FUNC.BCO DO BRASIL( PREVI)", users: 25, revenue: 71490 },
  { vertical: "FINANCEIRO I", name: "GOLDMAN SACHS DO BRASIL BANCO MULTIPLO", users: 27, revenue: 71207 },
  { vertical: "FINANCEIRO I", name: "BANCO JP MORGAN", users: 30, revenue: 65858 },
  { vertical: "GOVERNO", name: "FUNDACAO PETROS", users: 32, revenue: 62385 },
  { vertical: "AGRO/CORP", name: "BANSICREDI", users: 24, revenue: 60095 },
  { vertical: "FINANCEIRO I", name: "BANCO BMG", users: 19, revenue: 59931 },
  { vertical: "GOVERNO", name: "PRESIDENCIA DA REPUBLICA", users: 30, revenue: 59277 },
  { vertical: "FINANCEIRO II", name: "BANCO BOCOM BBM S.A.", users: 23, revenue: 59083 },
  { vertical: "FINANCEIRO II", name: "BANK OF AMERICA MERRILL LYNCH BANCO MULTIPLO S.A.", users: 18, revenue: 58566 },
  { vertical: "AGRO/CORP", name: "SAO MARTINHO", users: 16, revenue: 57913 },
  { vertical: "FINANCEIRO II", name: "UBS BRASIL ASSESSORIA FINANCEIRA", users: 29, revenue: 55940 },
  { vertical: "AGRO/CORP", name: "NOBLE BRASIL", users: 23, revenue: 55936 },
  { vertical: "FINANCEIRO II", name: "BANCO MERCANTIL", users: 19, revenue: 51830 },
  { vertical: "AGRO/CORP", name: "BANCO SICOOB", users: 23, revenue: 49363 },
  { vertical: "FINANCEIRO I", name: "BANCO SOFISA SA", users: 10, revenue: 48058 },
  { vertical: "FINANCEIRO II", name: "ARX INVESTIMENTOS LTDA", users: 14, revenue: 45112 },
  { vertical: "FINANCEIRO II", name: "TRUSTEE DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA", users: 6, revenue: 44210 },
  { vertical: "FINANCEIRO II", name: "MIRAE ASSET (BRASIL) CORRETORA DE CAMBIO, TITULOS E VALORES MOBILIARIOS LTDA.", users: 9, revenue: 43639 },
  { vertical: "FINANCEIRO I", name: "TRAVELEX BANK", users: 105, revenue: 42509 },
  { vertical: "AGRO/CORP", name: "EVOLUA ETANOL", users: 4, revenue: 42180 },
  { vertical: "GOVERNO", name: "BRB - BANCO DE BRASILIA", users: 21, revenue: 42085 },
  { vertical: "FINANCEIRO I", name: "BNP BRASIL", users: 18, revenue: 41801 },
  { vertical: "FINANCEIRO II", name: "B3 BRASIL, BOLSA, BALCAO", users: 23, revenue: 41098 },
  { vertical: "FINANCEIRO II", name: "BANCO MIZUHO DO BRASIL", users: 16, revenue: 40673 },
  { vertical: "AGRO/CORP", name: "CONFEDERACAO SICREDI", users: 20, revenue: 40647 },
  { vertical: "FINANCEIRO I", name: "BANCO PINE S/A", users: 22, revenue: 40287 },
  { vertical: "AGRO/CORP", name: "MINERVA S.A.", users: 19, revenue: 40079 },
  { vertical: "AGRO/CORP", name: "ELETROBRAS", users: 16, revenue: 40075 },
  { vertical: "FINANCEIRO I", name: "ASA INVESTMENTS", users: 27, revenue: 39170 },
  { vertical: "FINANCEIRO II", name: "BANCO INDUSTRIAL DO BRASIL", users: 12, revenue: 38668 },
  { vertical: "FINANCEIRO II", name: "SUL AMERICA INVESTIMENTOS DTVM", users: 23, revenue: 37925 },
  { vertical: "FINANCEIRO II", name: "FEBRABAN", users: 9, revenue: 37839 },
  { vertical: "GOVERNO", name: "BRASILPREV SEGUROS E PREVIDENCIA", users: 23, revenue: 37540 },
  { vertical: "AGRO/CORP", name: "OURO SAFRA S/A", users: 24, revenue: 37410 },
  { vertical: "GOVERNO", name: "FUNCEF", users: 23, revenue: 36848 },
  { vertical: "AGRO/CORP", name: "NKG STOCKLER", users: 19, revenue: 36714 },
  { vertical: "FINANCEIRO II", name: "BW GESTAO DE INVESTIMENTOS", users: 8, revenue: 36166 },
  { vertical: "FINANCEIRO I", name: "BNP PARIBAS ASSET MANAGEMENT BRASIL LTDA", users: 14, revenue: 35073 },
  { vertical: "FINANCEIRO II", name: "BANCO OURINVEST S/A", users: 29, revenue: 34781 },
  { vertical: "FINANCEIRO II", name: "GENOA CAPITAL GESTORA DE RECURSOS LTDA", users: 15, revenue: 33261 },
  { vertical: "GOVERNO", name: "PETROBRAS BIOCOMBUSTIVEL", users: 16, revenue: 33036 },
  { vertical: "AGRO/CORP", name: "CARGILL", users: 148, revenue: 32487 },
  { vertical: "AGRO/CORP", name: "ULTRAPAR", users: 14, revenue: 32458 },
  { vertical: "AGRO/CORP", name: "BANCO RABOBANK INTERNATIONAL BRASIL", users: 17, revenue: 32103 },
  { vertical: "AGRO/CORP", name: "TELEFONICA", users: 23, revenue: 30691 },
  { vertical: "FINANCEIRO II", name: "BANCO RENDIMENTO", users: 15, revenue: 30463 },
  { vertical: "FINANCEIRO II", name: "CREDIT SUISSE", users: 14, revenue: 30380 },
  { vertical: "GOVERNO", name: "FUNPRESP", users: 16, revenue: 30356 },
  { vertical: "FINANCEIRO II", name: "ICATU VANGUARDA", users: 11, revenue: 30204 },
  { vertical: "AGRO/CORP", name: "B3 BRASIL, BOLSA, BALCAO", users: 1, revenue: 30000 },
  { vertical: "AGRO/CORP", name: "COAMO AGROINDUSTRIAL COOPERATIVA", users: 18, revenue: 29711 },
  { vertical: "AGRO/CORP", name: "CSN", users: 12, revenue: 29610 },
  { vertical: "AGRO/CORP", name: "COCCAMIG", users: 22, revenue: 29595 },
  { vertical: "FINANCEIRO II", name: "BR PARTNERS BANCO DE INVESTIMENTO S.A.", users: 17, revenue: 28390 },
  { vertical: "FINANCEIRO II", name: "BANCO DAYCOVAL SA", users: 17, revenue: 28005 },
  { vertical: "FINANCEIRO II", name: "AZ QUEST INVESTIMENTOS", users: 14, revenue: 27803 },
  { vertical: "AGRO/CORP", name: "CHS AGRONEGÓCIO - INDUSTRIA E COMERCIO LTDA.", users: 18, revenue: 27720 },
  { vertical: "FINANCEIRO II", name: "OPPORTUNITTY GESTORA", users: 8, revenue: 26984 },
  { vertical: "FINANCEIRO I", name: "BANCO FIBRA", users: 14, revenue: 26682 },
  { vertical: "AGRO/CORP", name: "CJ INTERNATIONAL BRASIL COMERCIAL AGRICOLA", users: 14, revenue: 26501 },
  { vertical: "FINANCEIRO I", name: "TIVIO", users: 15, revenue: 26201 },
  { vertical: "FINANCEIRO I", name: "PORTO SEGURO INVESTIMENTOS LTDA", users: 14, revenue: 24685 },
  { vertical: "AGRO/CORP", name: "BRF S.A.", users: 34, revenue: 23907 },
  { vertical: "FINANCEIRO II", name: "BOC BRASIL", users: 14, revenue: 23677 },
  { vertical: "GOVERNO", name: "BANCO DA AMAZONIA", users: 13, revenue: 23059 },
  { vertical: "AGRO/CORP", name: "FERTIPAR", users: 12, revenue: 22956 },
  { vertical: "AGRO/CORP", name: "NOVAAGRI", users: 41, revenue: 22839 },
  { vertical: "FINANCEIRO II", name: "INTER DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", users: 12, revenue: 22748 },
  { vertical: "FINANCEIRO II", name: "SPX GESTAO DE RECURSOS", users: 6, revenue: 22727 },
  { vertical: "FINANCEIRO II", name: "MORGAN STANLEY DO BRASIL", users: 8, revenue: 22684 },
  { vertical: "AGRO/CORP", name: "BANCO HONDA", users: 7, revenue: 22261 },
  { vertical: "AGRO/CORP", name: "MARFRIG", users: 8, revenue: 22238 },
  { vertical: "FINANCEIRO II", name: "VINLAND CAPITAL MANAGEMENT GESTORA DE RECURSOS LTDA", users: 10, revenue: 22234 },
  { vertical: "GOVERNO", name: "BANPARA", users: 8, revenue: 21939 },
  { vertical: "FINANCEIRO II", name: "VINCI GESTORA DE RECURSOS LTDA", users: 7, revenue: 21845 },
  { vertical: "AGRO/CORP", name: "VALE", users: 2, revenue: 21822 },
  { vertical: "FINANCEIRO II", name: "PROTEUS INVESTIMENTOS LTDA", users: 8, revenue: 21753 },
  { vertical: "AGRO/CORP", name: "CPFL ENERGIA S.A.", users: 11, revenue: 21509 },
  { vertical: "GOVERNO", name: "MINISTERIO DE MINAS E ENERGIA", users: 12, revenue: 21249 },
  { vertical: "FINANCEIRO II", name: "TERRA INVESTIMENTOS", users: 9, revenue: 20730 },
  { vertical: "GOVERNO", name: "CAIXA SEGURIDADE", users: 9, revenue: 20381 },
  { vertical: "FINANCEIRO II", name: "TRUXT INVESTIMENTOS LTDA", users: 5, revenue: 20136 },
  { vertical: "GOVERNO", name: "GABINETE DO MINISTRO", users: 10, revenue: 20100 },
  { vertical: "AGRO/CORP", name: "JHSF PARTICIPACOES SA", users: 8, revenue: 19890 },
  { vertical: "FINANCEIRO II", name: "INVESTCOOP ASSET MANAGEMENT LTDA", users: 9, revenue: 19804 },
  { vertical: "FINANCEIRO II", name: "ANBIMA", users: 8, revenue: 19736 },
  { vertical: "AGRO/CORP", name: "FUNDACAO CESP", users: 9, revenue: 19612 },
  { vertical: "AGRO/CORP", name: "MAREX SOLUTIONS", users: 9, revenue: 19581 },
  { vertical: "FINANCEIRO II", name: "GALAPAGOS CAPITAL INVESTIMENTOS E PARTICIPACOES LTDA", users: 11, revenue: 19396 },
  { vertical: "FINANCEIRO II", name: "SCOTIABANK BRASIL S/A BANCO MULTIPLO", users: 11, revenue: 19288 },
  { vertical: "FINANCEIRO II", name: "KAPITALO INVESTIMENTOS", users: 7, revenue: 19210 },
  { vertical: "AGRO/CORP", name: "VOTORANTIM", users: 8, revenue: 19119 },
  { vertical: "AGRO/CORP", name: "INVISTA COMERCIO DE CEREAIS", users: 7, revenue: 18989 },
  { vertical: "FINANCEIRO II", name: "BANCO AGIBANK S.A", users: 20, revenue: 18938 },
  { vertical: "FINANCEIRO II", name: "IRB BRASIL RE", users: 8, revenue: 18915 },
  { vertical: "AGRO/CORP", name: "BELAGRICOLA", users: 5, revenue: 18805 },
  { vertical: "FINANCEIRO I", name: "PICPAY", users: 8, revenue: 18493 },
  { vertical: "FINANCEIRO II", name: "NOMAD TECNOLOGIA E PARTICIPACOES LTDA.", users: 3, revenue: 18119 },
  { vertical: "AGRO/CORP", name: "LOUIS DREYFUS COMPANY BRASIL S.A", users: 35, revenue: 17710 },
  { vertical: "FINANCEIRO I", name: "Bba", users: 1, revenue: 17651 },
  { vertical: "AGRO/CORP", name: "C. VALE", users: 11, revenue: 17511 },
  { vertical: "FINANCEIRO II", name: "BANCO PAULISTA", users: 12, revenue: 17479 },
  { vertical: "AGRO/CORP", name: "BRF S.A", users: 7, revenue: 17256 },
  { vertical: "AGRO/CORP", name: "TRES TENTOS AGROINDUSTRIAL LTDA", users: 6, revenue: 17220 },
  { vertical: "FINANCEIRO II", name: "JAIME PINHEIRO", users: 5, revenue: 17095 },
  { vertical: "AGRO/CORP", name: "SOYBRASIL AGRO TRADING LTDA", users: 11, revenue: 17046 },
  { vertical: "GOVERNO", name: "STJ", users: 26, revenue: 17012 },
  { vertical: "GOVERNO", name: "PREVIC", users: 9, revenue: 16705 },
  { vertical: "FINANCEIRO II", name: "VERDE ASSET MANAGEMENT", users: 12, revenue: 16613 },
  { vertical: "GOVERNO", name: "BB NEW YORK BRANCH", users: 5, revenue: 16449 },
  { vertical: "GOVERNO", name: "BDMG", users: 7, revenue: 16422 },
  { vertical: "AGRO/CORP", name: "VICUNHA TEXTIL", users: 5, revenue: 16411 },
  { vertical: "AGRO/CORP", name: "STONEX CONSULTORIA EM FUTUROS E COMMODITIES LTDA.", users: 9, revenue: 16252 },
  { vertical: "GOVERNO", name: "CENTRUS", users: 9, revenue: 16026 },
  { vertical: "FINANCEIRO II", name: "BANCO FATOR SA", users: 9, revenue: 15977 },
  { vertical: "FINANCEIRO II", name: "AZIMUT BRASIL DTVM", users: 8, revenue: 15845 },
  { vertical: "AGRO/CORP", name: "KLABIN", users: 7, revenue: 15843 },
  { vertical: "GOVERNO", name: "YARDS ASSET", users: 7, revenue: 15721 },
  { vertical: "FINANCEIRO II", name: "BANCO CREDIT AGRICOLE BRASIL S.A.", users: 9, revenue: 15707 },
  { vertical: "AGRO/CORP", name: "VIBRA ENERGIA S.A", users: 5, revenue: 15692 },
  { vertical: "FINANCEIRO II", name: "BANCO BS2 S.A.", users: 12, revenue: 15467 },
  { vertical: "AGRO/CORP", name: "ACUCAR E ALCOOL OSWALDO RIBEIRO", users: 4, revenue: 15221 },
  { vertical: "FINANCEIRO II", name: "DEUTSCHE BANK", users: 8, revenue: 14900 },
  { vertical: "FINANCEIRO II", name: "BANCO CAIXA GERAL - BRASIL S.A.", users: 10, revenue: 14717 },
  { vertical: "FINANCEIRO II", name: "MONGERAL AEGON", users: 7, revenue: 14661 },
  { vertical: "FINANCEIRO II", name: "NOVA FUTURA CORRETORA", users: 5, revenue: 14495 },
  { vertical: "GOVERNO", name: "FUNPRESP-JUD", users: 5, revenue: 14471 },
  { vertical: "FINANCEIRO II", name: "CLARITAS ADMINISTRAÇÃO DE RECURSOS LTDA", users: 13, revenue: 14464 },
  { vertical: "FINANCEIRO II", name: "MAPFRE INVESTIMENTOS LTDA.", users: 9, revenue: 14445 },
  { vertical: "AGRO/CORP", name: "E D & F MAN BRASIL", users: 7, revenue: 14379 },
  { vertical: "GOVERNO", name: "CEMIG CIA ENERGETICA DE MG", users: 5, revenue: 14361 },
  { vertical: "AGRO/CORP", name: "GRENDENE", users: 5, revenue: 14326 },
  { vertical: "FINANCEIRO II", name: "SAGA CONSULTORIA", users: 6, revenue: 14243 },
  { vertical: "AGRO/CORP", name: "COOPERATIVA AGRARIA AGROINDUSTRIAL", users: 11, revenue: 14239 },
  { vertical: "FINANCEIRO II", name: "NECTON INVESTIMENTOS SP", users: 11, revenue: 14178 },
  { vertical: "AGRO/CORP", name: "SUZANO PAPEL E CELULOSE", users: 3, revenue: 14042 },
  { vertical: "GOVERNO", name: "FACHESF", users: 6, revenue: 13934 },
  { vertical: "AGRO/CORP", name: "CCR CIA DE CONCESSOES RODOVIARIAS", users: 5, revenue: 13711 },
  { vertical: "AGRO/CORP", name: "BREJEIRO", users: 5, revenue: 13498 },
  { vertical: "AGRO/CORP", name: "AEGEA SANEAMENTO E PARTICIPACOES", users: 6, revenue: 13429 },
  { vertical: "FINANCEIRO II", name: "SCHRODER INVESTMENT MANAGEMENT BRASIL DTVM", users: 7, revenue: 13395 },
  { vertical: "GOVERNO", name: "PREVIMPA/UFIN", users: 5, revenue: 13261 },
  { vertical: "FINANCEIRO I", name: "BANCO ORIGINAL", users: 5, revenue: 13161 },
  { vertical: "FINANCEIRO II", name: "LEGACY CAPITAL GESTORA DE RECURSOS", users: 6, revenue: 13048 },
  { vertical: "AGRO/CORP", name: "UNIPAR CARBOCLORO S/A.", users: 7, revenue: 13016 },
  { vertical: "FINANCEIRO II", name: "FUNDACAO ATLANTICO DE SEGURIDADE SOCIAL", users: 5, revenue: 12995 },
  { vertical: "AGRO/CORP", name: "COMEXIM", users: 8, revenue: 12788 },
  { vertical: "FINANCEIRO I", name: "SANTANDER BRASIL GESTAO DE RECURSOS LTDA", users: 2, revenue: 12763 },
  { vertical: "AGRO/CORP", name: "JACOBS DOUWE EGBERTS BR COMERCIALIZACAO DE CAFES", users: 6, revenue: 12749 },
  { vertical: "FINANCEIRO II", name: "FORPUS CAPITAL GESTÃO DE RECURSOS LTDA", users: 4, revenue: 12741 },
  { vertical: "AGRO/CORP", name: "BE8 S.A.", users: 6, revenue: 12708 },
  { vertical: "FINANCEIRO II", name: "PLANNER CORRETORA DE VALORES", users: 8, revenue: 12700 },
  { vertical: "AGRO/CORP", name: "MARUBENI GRÃOS BRASIL", users: 6, revenue: 12692 },
  { vertical: "AGRO/CORP", name: "SINOVA INOVACOES AGRICOLAS", users: 3, revenue: 12663 },
  { vertical: "GOVERNO", name: "COPASA", users: 6, revenue: 12567 },
  { vertical: "AGRO/CORP", name: "CATENO", users: 4, revenue: 12396 },
  { vertical: "FINANCEIRO II", name: "NORTE ASSET MANAGEMENT GESTAO DE RECURSOS", users: 4, revenue: 12199 },
  { vertical: "AGRO/CORP", name: "FRIBOI", users: 4, revenue: 12187 },
  { vertical: "FINANCEIRO II", name: "BTG PACTUAL CORRETORA", users: 27, revenue: 12118 },
  { vertical: "FINANCEIRO II", name: "BBVA", users: 5, revenue: 11998 },
  { vertical: "GOVERNO", name: "PREVIG", users: 5, revenue: 11984 },
  { vertical: "FINANCEIRO II", name: "JGP", users: 3, revenue: 11979 },
  { vertical: "AGRO/CORP", name: "NEOENERGIA", users: 6, revenue: 11952 },
  { vertical: "FINANCEIRO I", name: "HSBC GLOBAL SERVICES LIMITED (UK)", users: 7, revenue: 11909 },
  { vertical: "FINANCEIRO II", name: "BANCO C6 SA", users: 7, revenue: 11610 },
  { vertical: "AGRO/CORP", name: "COPEL", users: 4, revenue: 11428 },
  { vertical: "AGRO/CORP", name: "SLC PARTICIPACOES S.A.", users: 4, revenue: 11417 },
  { vertical: "AGRO/CORP", name: "EMBRAER", users: 6, revenue: 11415 },
  { vertical: "GOVERNO", name: "TCU", users: 6, revenue: 11266 },
  { vertical: "AGRO/CORP", name: "ADM DO BRASIL LTDA", users: 3, revenue: 11265 },
  { vertical: "FINANCEIRO II", name: "BANCO GUANABARA", users: 7, revenue: 11196 },
  { vertical: "AGRO/CORP", name: "CASTROLANDA - COOPERATIVA AGROINDUSTRIAL", users: 6, revenue: 11127 },
  { vertical: "FINANCEIRO II", name: "SAG INVESTIMENTOS", users: 3, revenue: 11120 },
  { vertical: "GOVERNO", name: "CAIXA VIDA E PREVIDENCIA", users: 7, revenue: 11096 },
  { vertical: "GOVERNO", name: "CAMARA DOS DEPUTADOS", users: 6, revenue: 11072 },
  { vertical: "FINANCEIRO II", name: "RB CAPITAL ASSET MANAGEMENT LTDA", users: 10, revenue: 11039 },
  { vertical: "GOVERNO", name: "BRASILCAP CAPITALIZACAO", users: 7, revenue: 11021 },
  { vertical: "FINANCEIRO II", name: "REAL INVESTOR", users: 12, revenue: 11002 },
  { vertical: "FINANCEIRO II", name: "PAGSEGURO INTERNET", users: 6, revenue: 10937 },
  { vertical: "AGRO/CORP", name: "BANCO YAMAHA MOTOR DO BRASIL", users: 3, revenue: 10840 },
  { vertical: "AGRO/CORP", name: "BRAVA ENERGIA", users: 6, revenue: 10835 },
  { vertical: "AGRO/CORP", name: "USINA SANTO ANGELO", users: 4, revenue: 10759 },
  { vertical: "GOVERNO", name: "CONFEDERACAO NACIONAL DO COMERCIO", users: 3, revenue: 10600 },
  { vertical: "AGRO/CORP", name: "COPERSUCAR", users: 3, revenue: 10451 },
  { vertical: "FINANCEIRO I", name: "ITAUSA S.A.", users: 5, revenue: 10433 },
  { vertical: "AGRO/CORP", name: "RAIZEN ENERGIA", users: 4, revenue: 10428 },
  { vertical: "AGRO/CORP", name: "MERCURIO FRIGORIFICO", users: 4, revenue: 10376 },
  { vertical: "AGRO/CORP", name: "FIASA", users: 5, revenue: 10348 },
  { vertical: "AGRO/CORP", name: "SERTRADING", users: 4, revenue: 10335 },
  { vertical: "FINANCEIRO II", name: "MESSEM INVESTIMENTOS", users: 7, revenue: 10262 },
  { vertical: "AGRO/CORP", name: "AGROFERTIL S.A.", users: 18, revenue: 10249 },
  { vertical: "FINANCEIRO II", name: "MONTE AZUL GESTAO DE RECURSOS LTDA", users: 7, revenue: 10208 },
  { vertical: "AGRO/CORP", name: "CUTRALE", users: 4, revenue: 10204 },
  { vertical: "FINANCEIRO I", name: "HERTSHTEN GROUP LTD", users: 10, revenue: 10200 },
  { vertical: "AGRO/CORP", name: "VISAO PREV.", users: 5, revenue: 10163 },
  { vertical: "FINANCEIRO II", name: "MONTE BRAVO CORRETORA", users: 5, revenue: 10158 },
  { vertical: "AGRO/CORP", name: "MAQUINAS AGRICOLAS JACTO", users: 7, revenue: 10137 },
  { vertical: "FINANCEIRO II", name: "PREVIRB", users: 3, revenue: 10121 },
  { vertical: "FINANCEIRO I", name: "GUIDE INVESTIMENTOS", users: 6, revenue: 10096 },
  { vertical: "GOVERNO", name: "FORLUZ", users: 5, revenue: 10062 },
];
